# -*- coding: utf-8 -*-
"""1_exploration_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dVBFdq8q3IKjk10_aS_MoZ4ZSpZbith
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import make_interp_spline
import glob
import os

from src.config import settings


# Leggi la lista dei ticker dal file
def load_tickers_only(filename='tickers.txt'):
    """Carica solo i ticker dal file di configurazione"""
    tickers = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                parts = line.split(',')
                if len(parts) == 2:
                    ticker = parts[1].strip()
                    tickers.append(ticker)
    return tickers


TICKERS = load_tickers_only('tickers.txt')

# Crea la cartella result se non esiste
settings.RESULT_DIR.mkdir(parents=True, exist_ok=True)

# PLOT DATI TRIMESTRALI (10-Q)
print("=" * 80)
print("GENERAZIONE GRAFICI TRIMESTRALI (10-Q)")
print("=" * 80)

plt.style.use('seaborn-v0_8')

for ticker in TICKERS:
    filename = f"data/{ticker}_fcf_10Q.csv"

    if os.path.exists(filename):
        # Leggi il CSV
        df = pd.read_csv(filename)

        if not df.empty:
            # Converti date e ordina
            df['end'] = pd.to_datetime(df['end'])
            df = df.sort_values('end')

            # Converti FCF in miliardi e rimuovi NaN
            df['FCF_B'] = df['Free Cash Flow'] / 1_000_000_000
            df = df.dropna(subset=['end', 'FCF_B'])

            # Deduplica per fiscal year (keep last filing)
            if 'fy' in df.columns:
                df = df.sort_values(['fy', 'end'])
                df = df.drop_duplicates(subset=['fy'], keep='last')

            # Crea plot individuale
            plt.figure(figsize=(12, 6))

            # Smooth interpolation
            fy_vals = df['end'].values
            fcf_vals = df['FCF_B'].values

            if len(fy_vals) > 3:
                # Create smooth curve
                x_smooth = np.linspace(0, len(fy_vals) - 1, 300)
                spl = make_interp_spline(range(len(fy_vals)), fcf_vals, k=3)
                fcf_smooth = spl(x_smooth)
                x_dates_smooth = np.interp(x_smooth, range(len(fy_vals)),
                                           [pd.Timestamp(d).timestamp() for d in fy_vals])
                dates_smooth = pd.to_datetime(x_dates_smooth, unit='s')

                plt.plot(dates_smooth, fcf_smooth, linewidth=2, color='steelblue')

            plt.plot(df['end'], df['FCF_B'], marker='o', markersize=6,
                     color='steelblue', linestyle='')

            plt.title(f'{ticker} - Quarterly Free Cash Flow (10-Q)', fontsize=16, fontweight='bold')
            plt.xlabel('Date', fontsize=12)
            plt.ylabel('Free Cash Flow ($B)', fontsize=12)
            plt.grid(True, alpha=0.3)
            plt.xticks(rotation=45)

            # Aggiungi ultimo valore
            last_value = df['FCF_B'].iloc[-1]
            last_year = int(df['fy'].iloc[-1])

            # Check if 'fp' column exists
            if 'fp' in df.columns:
                last_period = df['fp'].iloc[-1]
                label_text = f'Latest: ${last_value:.1f}B ({last_period} FY{last_year})'
            else:
                label_text = f'Latest: ${last_value:.1f}B (FY{last_year})'

            plt.text(0.02, 0.98, label_text,
                     transform=plt.gca().transAxes, fontsize=12,
                     verticalalignment='top', bbox=dict(boxstyle='round',
                                                        facecolor='lightblue', alpha=0.8))

            plt.tight_layout()
            plt.savefig(settings.RESULT_DIR / f'{ticker}_fcf_10Q.png', dpi=300, bbox_inches='tight')
            plt.show()

            print(f"✓ Grafico 10-Q salvato: result/{ticker}_fcf_10Q.png")
        else:
            print(f"⚠ {ticker}: File 10-Q vuoto")
    else:
        print(f"✗ {ticker}: File {filename} non trovato")

print("\n✓ Tutti i grafici trimestrali (10-Q) completati")

# PLOT DATI ANNUALI (10-K)
print("\n" + "=" * 80)
print("GENERAZIONE GRAFICI ANNUALI (10-K)")
print("=" * 80)

plt.style.use('seaborn-v0_8')

for ticker in TICKERS:
    filename = f"data/{ticker}_fcf_10K.csv"

    if os.path.exists(filename):
        # Leggi il CSV
        df = pd.read_csv(filename)

        if not df.empty:
            # Converti date e ordina
            df['end'] = pd.to_datetime(df['end'])
            df = df.sort_values('end')

            # Converti FCF in miliardi e rimuovi NaN
            df['FCF_B'] = df['Free Cash Flow'] / 1_000_000_000
            df = df.dropna(subset=['end', 'FCF_B'])

            # Deduplica per fiscal year (keep last filing)
            if 'fy' in df.columns:
                df = df.sort_values(['fy', 'end'])
                df = df.drop_duplicates(subset=['fy'], keep='last')

            # Crea plot individuale
            plt.figure(figsize=(12, 6))

            # Smooth interpolation
            fy_vals = df['end'].values
            fcf_vals = df['FCF_B'].values

            if len(fy_vals) > 3:
                # Create smooth curve
                x_smooth = np.linspace(0, len(fy_vals) - 1, 300)
                spl = make_interp_spline(range(len(fy_vals)), fcf_vals, k=3)
                fcf_smooth = spl(x_smooth)
                x_dates_smooth = np.interp(x_smooth, range(len(fy_vals)),
                                           [pd.Timestamp(d).timestamp() for d in fy_vals])
                dates_smooth = pd.to_datetime(x_dates_smooth, unit='s')

                plt.plot(dates_smooth, fcf_smooth, linewidth=2, color='darkgreen')

            plt.plot(df['end'], df['FCF_B'], marker='s', markersize=8,
                     color='darkgreen', linestyle='')

            plt.title(f'{ticker} - Annual Free Cash Flow (10-K)', fontsize=16, fontweight='bold')
            plt.xlabel('Date', fontsize=12)
            plt.ylabel('Free Cash Flow ($B)', fontsize=12)
            plt.grid(True, alpha=0.3)
            plt.xticks(rotation=45)

            # Aggiungi ultimo valore
            last_value = df['FCF_B'].iloc[-1]
            last_year = int(df['fy'].iloc[-1])
            plt.text(0.02, 0.98, f'Latest: ${last_value:.1f}B (FY{last_year})',
                     transform=plt.gca().transAxes, fontsize=12,
                     verticalalignment='top', bbox=dict(boxstyle='round',
                                                        facecolor='lightgreen', alpha=0.8))

            plt.tight_layout()
            plt.savefig(settings.RESULT_DIR / f'{ticker}_fcf_10K.png', dpi=300, bbox_inches='tight')
            plt.show()

            print(f"✓ Grafico 10-K salvato: result/{ticker}_fcf_10K.png")
        else:
            print(f"⚠ {ticker}: File 10-K vuoto")
    else:
        print(f"✗ {ticker}: File {filename} non trovato")

print("\n✓ Tutti i grafici annuali (10-K) completati")
print("\n" + "=" * 80)
print("ANALISI COMPLETATA")
print("=" * 80)